server:
  port: 8761
eureka:
  instance:
    hostname: discovery-service
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
spring:
  application:
    name: discovery-service